from __future__ import annotations

from typing import Any, Protocol


class StateStorage(Protocol):
    def get_state(self) -> str | None: ...
    def change_state(self, state: str) -> None: ...
    def get_data(self) -> dict[str, Any] | None: ...
    def change_data(self, data: dict[str, Any]) -> None: ...
    def clear(self) -> None: ...
