"""added gis_id to users

Revision ID: 4fa7e5037a90
Revises: 8f36bee1f7c3
Create Date: 2026-06-07 18:27:45.608001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa7e5037a90'
down_revision: Union[str, Sequence[str], None] = '8f36bee1f7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gis_user_id', sa.Integer(), nullable=True))
    op.create_index('ix_users_gis_user_id', 'users', ['gis_user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_gis_user_id'), 'users', ['gis_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_gis_user_id'), 'users', type_='unique')
    op.drop_index('ix_users_gis_user_id', table_name='users')
    op.drop_column('users', 'gis_user_id')
    # ### end Alembic commands ###
