"""edited models

Revision ID: 6155388b7f36
Revises: 4fa7e5037a90
Create Date: 2026-06-09 22:38:54.826950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6155388b7f36'
down_revision: Union[str, Sequence[str], None] = '4fa7e5037a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_refs', sa.Column('photo_url', sa.String(length=1024), nullable=True))
    op.alter_column(
        "object_refs",
        "responsible_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="responsible_id::uuid",
    )
    op.create_index(
        'ix_object_refs_responsible_id',
        'object_refs',
        ['responsible_id'],
        unique=False
    )
    op.create_foreign_key(
        op.f('fk_object_refs_responsible_id_users'),
        'object_refs',
        'users',
        ['responsible_id'],
        ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_object_refs_responsible_id_users'), 'object_refs', type_='foreignkey')
    op.drop_index('ix_object_refs_responsible_id', table_name='object_refs')
    op.alter_column('object_refs', 'responsible_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('object_refs', 'photo_url')
    # ### end Alembic commands ###
