"""create initial tables

Revision ID: 8f36bee1f7c3
Revises: 
Create Date: 2026-06-06 13:59:08.938347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f36bee1f7c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_refs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('responsible_external_id', sa.String(length=255), nullable=True),
    sa.Column('responsible_id', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_object_refs')),
    sa.UniqueConstraint('code', name=op.f('uq_object_refs_code')),
    sa.UniqueConstraint('external_id', name=op.f('uq_object_refs_external_id'))
    )
    op.create_index('ix_object_refs_cached_at', 'object_refs', ['cached_at'], unique=False)
    op.create_index('ix_object_refs_code', 'object_refs', ['code'], unique=False)
    op.create_index('ix_object_refs_end_date', 'object_refs', ['end_date'], unique=False)
    op.create_index('ix_object_refs_external_id', 'object_refs', ['external_id'], unique=False)
    op.create_index('ix_object_refs_responsible_external_id', 'object_refs', ['responsible_external_id'], unique=False)
    op.create_index('ix_object_refs_source_updated_at', 'object_refs', ['source_updated_at'], unique=False)
    op.create_index('ix_object_refs_start_date', 'object_refs', ['start_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('messenger_user_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('messenger_user_id', name=op.f('uq_users_messenger_user_id')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_index('ix_users_messenger_user_id', 'users', ['messenger_user_id'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('object_ref_id', sa.UUID(), nullable=True),
    sa.Column('target_type', sa.String(length=128), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.ForeignKeyConstraint(['object_ref_id'], ['object_refs.id'], name=op.f('fk_audit_logs_object_ref_id_object_refs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('ix_audit_logs_object_ref_id', 'audit_logs', ['object_ref_id'], unique=False)
    op.create_index('ix_audit_logs_target_id', 'audit_logs', ['target_id'], unique=False)
    op.create_index('ix_audit_logs_target_type', 'audit_logs', ['target_type'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_ref_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('comment_type', sa.Enum('comment', 'photo_report', name='object_comment_type', native_enum=False, create_constraint=True), server_default='comment', nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['object_ref_id'], ['object_refs.id'], name=op.f('fk_comments_object_ref_id_object_refs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index('ix_comments_author_id', 'comments', ['author_id'], unique=False)
    op.create_index('ix_comments_created_at', 'comments', ['created_at'], unique=False)
    op.create_index('ix_comments_deleted_at', 'comments', ['deleted_at'], unique=False)
    op.create_index('ix_comments_object_ref_id', 'comments', ['object_ref_id'], unique=False)
    op.create_table('status_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_ref_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=64), nullable=True),
    sa.Column('new_status', sa.String(length=64), nullable=False),
    sa.Column('confirmation_status', sa.String(length=64), server_default='pending', nullable=False),
    sa.Column('confirmed_by_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_status_changes_author_id_users')),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], name=op.f('fk_status_changes_confirmed_by_id_users')),
    sa.ForeignKeyConstraint(['object_ref_id'], ['object_refs.id'], name=op.f('fk_status_changes_object_ref_id_object_refs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_changes'))
    )
    op.create_index('ix_status_changes_author_id', 'status_changes', ['author_id'], unique=False)
    op.create_index('ix_status_changes_confirmation_status', 'status_changes', ['confirmation_status'], unique=False)
    op.create_index('ix_status_changes_confirmed_at', 'status_changes', ['confirmed_at'], unique=False)
    op.create_index('ix_status_changes_confirmed_by_id', 'status_changes', ['confirmed_by_id'], unique=False)
    op.create_index('ix_status_changes_created_at', 'status_changes', ['created_at'], unique=False)
    op.create_index('ix_status_changes_object_ref_id', 'status_changes', ['object_ref_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_log_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], name=op.f('fk_notifications_audit_log_id_audit_logs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_audit_log_recipients_audit_log_id', 'notifications', ['audit_log_id'], unique=False)
    op.create_index('ix_audit_log_recipients_recipient_id', 'notifications', ['recipient_id'], unique=False)
    op.create_index('ix_audit_log_recipients_sent_at', 'notifications', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_recipients_sent_at', table_name='notifications')
    op.drop_index('ix_audit_log_recipients_recipient_id', table_name='notifications')
    op.drop_index('ix_audit_log_recipients_audit_log_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_status_changes_object_ref_id', table_name='status_changes')
    op.drop_index('ix_status_changes_created_at', table_name='status_changes')
    op.drop_index('ix_status_changes_confirmed_by_id', table_name='status_changes')
    op.drop_index('ix_status_changes_confirmed_at', table_name='status_changes')
    op.drop_index('ix_status_changes_confirmation_status', table_name='status_changes')
    op.drop_index('ix_status_changes_author_id', table_name='status_changes')
    op.drop_table('status_changes')
    op.drop_index('ix_comments_object_ref_id', table_name='comments')
    op.drop_index('ix_comments_deleted_at', table_name='comments')
    op.drop_index('ix_comments_created_at', table_name='comments')
    op.drop_index('ix_comments_author_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_audit_logs_target_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_target_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_object_ref_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_messenger_user_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_object_refs_start_date', table_name='object_refs')
    op.drop_index('ix_object_refs_source_updated_at', table_name='object_refs')
    op.drop_index('ix_object_refs_responsible_external_id', table_name='object_refs')
    op.drop_index('ix_object_refs_external_id', table_name='object_refs')
    op.drop_index('ix_object_refs_end_date', table_name='object_refs')
    op.drop_index('ix_object_refs_code', table_name='object_refs')
    op.drop_index('ix_object_refs_cached_at', table_name='object_refs')
    op.drop_table('object_refs')
    # ### end Alembic commands ###
